apiVersion: v1
kind: Service
metadata:
  name: homeapp-service
  labels:
    app: homeapp
spec:
  type: LoadBalancer
  selector:
    app: homeapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
